name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test

      # ✅ Zip the report folder only if it exists
      - name: Zip Playwright HTML report if it exists
        if: always()
        run: |
          if [ -d "playwright-report" ]; then
            echo "Zipping report..."
            zip -r playwright-report.zip playwright-report
          else
            echo "No report folder found."
          fi

      # ✅ Upload the zipped artifact only if it was created
      - name: Upload Playwright report artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report.zip
          retention-days: 30
